"""
Table GUI

Function:
        This python file is responsible
        for executing core program functions
        and viewing the results for the user.
        Data is saved to files within the project
        directory.
"""
from scan import scan_img
from tabular_extract import extract_table
from PyQt5 import QtCore, QtGui, QtWidgets


# method for getting correct group number
def get_sec(sec_num):
    group_number = (sec_num // 7) + 1
    header_list = [str(group_number), str(sec_num)]
    return  header_list


# method that executes all project required functions
# in their respective order as per the project
# desired flow
def do_your_job(img_pth, path, sec, save, im_state):
    # convert image to scanned format
    if im_state == 1:
        scan_img(img_pth)

    # extract tabular data
    sec_table_list = extract_table(path, sec, save)

    # wrap text in the list before starting to write
    line_len = 18
    for i in range(len(sec_table_list)):
        if len(sec_table_list[i]) > line_len:
            numLines = len(sec_table_list[i]) // line_len
            seperatedLines = ""
            for j in range(numLines):
                if j != numLines - 1:
                    seperatedLines += sec_table_list[i][line_len * j : (line_len * j) + line_len] + '\n'
                else:
                    seperatedLines += sec_table_list[i][line_len * j:]
            sec_table_list[i] = seperatedLines

    return sec_table_list


class Ui_Dialog(object):
    def setupUi(self, Dialog, main_list):
        global_list = do_your_job(main_list[0], main_list[1], main_list[2], main_list[3], main_list[4])
        header_data = get_sec(main_list[2])

        Dialog.setObjectName("Dialog")
        Dialog.resize(1300, 485)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1301, 491))
        self.label.setObjectName("label")
        self.label_86 = QtWidgets.QLabel(Dialog)
        self.label_86.setGeometry(QtCore.QRect(310, 570, 301, 61))
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(Dialog)
        self.label_87.setGeometry(QtCore.QRect(710, 570, 301, 61))
        self.label_87.setObjectName("label_87")
        self.label_00 = QtWidgets.QLabel(Dialog)
        self.label_00.setGeometry(QtCore.QRect(60, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_00.setFont(font)
        self.label_00.setText(global_list[0])
        self.label_00.setAlignment(QtCore.Qt.AlignCenter)
        self.label_00.setWordWrap(True)
        self.label_00.setObjectName("label_00")
        self.label_01 = QtWidgets.QLabel(Dialog)
        self.label_01.setGeometry(QtCore.QRect(164, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_01.setFont(font)
        self.label_01.setText(global_list[1])
        self.label_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_01.setWordWrap(True)
        self.label_01.setObjectName("label_01")
        self.label_02 = QtWidgets.QLabel(Dialog)
        self.label_02.setGeometry(QtCore.QRect(270, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_02.setFont(font)
        self.label_02.setText(global_list[2])
        self.label_02.setAlignment(QtCore.Qt.AlignCenter)
        self.label_02.setWordWrap(True)
        self.label_02.setObjectName("label_02")
        self.label_03 = QtWidgets.QLabel(Dialog)
        self.label_03.setGeometry(QtCore.QRect(370, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_03.setFont(font)
        self.label_03.setText(global_list[3])
        self.label_03.setAlignment(QtCore.Qt.AlignCenter)
        self.label_03.setWordWrap(True)
        self.label_03.setObjectName("label_03")
        self.label_04 = QtWidgets.QLabel(Dialog)
        self.label_04.setGeometry(QtCore.QRect(477, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_04.setFont(font)
        self.label_04.setText(global_list[4])
        self.label_04.setAlignment(QtCore.Qt.AlignCenter)
        self.label_04.setWordWrap(True)
        self.label_04.setObjectName("label_04")
        self.label_05 = QtWidgets.QLabel(Dialog)
        self.label_05.setGeometry(QtCore.QRect(580, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_05.setFont(font)
        self.label_05.setText(global_list[5])
        self.label_05.setAlignment(QtCore.Qt.AlignCenter)
        self.label_05.setWordWrap(True)
        self.label_05.setObjectName("label_05")
        self.label_09 = QtWidgets.QLabel(Dialog)
        self.label_09.setGeometry(QtCore.QRect(997, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_09.setFont(font)
        self.label_09.setText(global_list[9])
        self.label_09.setAlignment(QtCore.Qt.AlignCenter)
        self.label_09.setWordWrap(True)
        self.label_09.setObjectName("label_09")
        self.label_08 = QtWidgets.QLabel(Dialog)
        self.label_08.setGeometry(QtCore.QRect(893, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_08.setFont(font)
        self.label_08.setText(global_list[8])
        self.label_08.setAlignment(QtCore.Qt.AlignCenter)
        self.label_08.setWordWrap(True)
        self.label_08.setObjectName("label_08")
        self.label_07 = QtWidgets.QLabel(Dialog)
        self.label_07.setGeometry(QtCore.QRect(790, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_07.setFont(font)
        self.label_07.setText(global_list[7])
        self.label_07.setAlignment(QtCore.Qt.AlignCenter)
        self.label_07.setWordWrap(True)
        self.label_07.setObjectName("label_07")
        self.label_06 = QtWidgets.QLabel(Dialog)
        self.label_06.setGeometry(QtCore.QRect(687, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_06.setFont(font)
        self.label_06.setText(global_list[6])
        self.label_06.setAlignment(QtCore.Qt.AlignCenter)
        self.label_06.setWordWrap(True)
        self.label_06.setObjectName("label_06")
        self.label_011 = QtWidgets.QLabel(Dialog)
        self.label_011.setGeometry(QtCore.QRect(1204, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_011.setFont(font)
        self.label_011.setText(global_list[11])
        self.label_011.setAlignment(QtCore.Qt.AlignCenter)
        self.label_011.setWordWrap(True)
        self.label_011.setObjectName("label_011")
        self.label_010 = QtWidgets.QLabel(Dialog)
        self.label_010.setGeometry(QtCore.QRect(1101, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_010.setFont(font)
        self.label_010.setText(global_list[10])
        self.label_010.setAlignment(QtCore.Qt.AlignCenter)
        self.label_010.setWordWrap(True)
        self.label_010.setObjectName("label_010")
        self.label_111 = QtWidgets.QLabel(Dialog)
        self.label_111.setGeometry(QtCore.QRect(1204, 130, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_111.setFont(font)
        self.label_111.setText(global_list[23])
        self.label_111.setAlignment(QtCore.Qt.AlignCenter)
        self.label_111.setWordWrap(True)
        self.label_111.setObjectName("label_111")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(997, 130, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setText(global_list[21])
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.label_110 = QtWidgets.QLabel(Dialog)
        self.label_110.setGeometry(QtCore.QRect(1101, 130, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_110.setFont(font)
        self.label_110.setText(global_list[22])
        self.label_110.setAlignment(QtCore.Qt.AlignCenter)
        self.label_110.setWordWrap(True)
        self.label_110.setObjectName("label_110")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(790, 130, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setText(global_list[19])
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(580, 130, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setText(global_list[17])
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(370, 130, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setText(global_list[15])
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(477, 130, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setText(global_list[16])
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(270, 130, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setText(global_list[14])
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(60, 130, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setText(global_list[12])
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(170, 130, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setText(global_list[13])
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(687, 130, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setText(global_list[18])
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(890, 130, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setText(global_list[20])
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(60, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setText(global_list[24])
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(687, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setText(global_list[30])
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.label_211 = QtWidgets.QLabel(Dialog)
        self.label_211.setGeometry(QtCore.QRect(1204, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_211.setFont(font)
        self.label_211.setText(global_list[35])
        self.label_211.setAlignment(QtCore.Qt.AlignCenter)
        self.label_211.setWordWrap(True)
        self.label_211.setObjectName("label_211")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(370, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setText(global_list[27])
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(580, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setText(global_list[29])
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.label_210 = QtWidgets.QLabel(Dialog)
        self.label_210.setGeometry(QtCore.QRect(1101, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_210.setFont(font)
        self.label_210.setText(global_list[34])
        self.label_210.setAlignment(QtCore.Qt.AlignCenter)
        self.label_210.setWordWrap(True)
        self.label_210.setObjectName("label_210")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(477, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setText(global_list[28])
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setGeometry(QtCore.QRect(997, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setText(global_list[33])
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(790, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setText(global_list[31])
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(270, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setText(global_list[26])
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(170, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setText(global_list[25])
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(890, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setText(global_list[32])
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.label_311 = QtWidgets.QLabel(Dialog)
        self.label_311.setGeometry(QtCore.QRect(1204, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_311.setFont(font)
        self.label_311.setText(global_list[47])
        self.label_311.setAlignment(QtCore.Qt.AlignCenter)
        self.label_311.setWordWrap(True)
        self.label_311.setObjectName("label_311")
        self.label_31 = QtWidgets.QLabel(Dialog)
        self.label_31.setGeometry(QtCore.QRect(170, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setText(global_list[37])
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName("label_31")
        self.label_35 = QtWidgets.QLabel(Dialog)
        self.label_35.setGeometry(QtCore.QRect(580, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setText(global_list[41])
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setWordWrap(True)
        self.label_35.setObjectName("label_35")
        self.label_38 = QtWidgets.QLabel(Dialog)
        self.label_38.setGeometry(QtCore.QRect(890, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setText(global_list[44])
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setGeometry(QtCore.QRect(270, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setText(global_list[38])
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.label_34 = QtWidgets.QLabel(Dialog)
        self.label_34.setGeometry(QtCore.QRect(477, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setText(global_list[40])
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setWordWrap(True)
        self.label_34.setObjectName("label_34")
        self.label_37 = QtWidgets.QLabel(Dialog)
        self.label_37.setGeometry(QtCore.QRect(790, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setText(global_list[43])
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setWordWrap(True)
        self.label_37.setObjectName("label_37")
        self.label_33 = QtWidgets.QLabel(Dialog)
        self.label_33.setGeometry(QtCore.QRect(370, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setText(global_list[39])
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setWordWrap(True)
        self.label_33.setObjectName("label_33")
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setGeometry(QtCore.QRect(60, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setText(global_list[36])
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.label_39 = QtWidgets.QLabel(Dialog)
        self.label_39.setGeometry(QtCore.QRect(997, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setText(global_list[45])
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setWordWrap(True)
        self.label_39.setObjectName("label_39")
        self.label_36 = QtWidgets.QLabel(Dialog)
        self.label_36.setGeometry(QtCore.QRect(687, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setText(global_list[42])
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setWordWrap(True)
        self.label_36.setObjectName("label_36")
        self.label_310 = QtWidgets.QLabel(Dialog)
        self.label_310.setGeometry(QtCore.QRect(1101, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_310.setFont(font)
        self.label_310.setText(global_list[46])
        self.label_310.setAlignment(QtCore.Qt.AlignCenter)
        self.label_310.setWordWrap(True)
        self.label_310.setObjectName("label_310")
        self.label_40 = QtWidgets.QLabel(Dialog)
        self.label_40.setGeometry(QtCore.QRect(60, 310, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setText(global_list[48])
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setWordWrap(True)
        self.label_40.setObjectName("label_40")
        self.label_410 = QtWidgets.QLabel(Dialog)
        self.label_410.setGeometry(QtCore.QRect(1102, 310, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_410.setFont(font)
        self.label_410.setText(global_list[58])
        self.label_410.setAlignment(QtCore.Qt.AlignCenter)
        self.label_410.setWordWrap(True)
        self.label_410.setObjectName("label_410")
        self.label_411 = QtWidgets.QLabel(Dialog)
        self.label_411.setGeometry(QtCore.QRect(1205, 310, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_411.setFont(font)
        self.label_411.setText(global_list[59])
        self.label_411.setAlignment(QtCore.Qt.AlignCenter)
        self.label_411.setWordWrap(True)
        self.label_411.setObjectName("label_411")
        self.label_41 = QtWidgets.QLabel(Dialog)
        self.label_41.setGeometry(QtCore.QRect(170, 310, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setText(global_list[49])
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setWordWrap(True)
        self.label_41.setObjectName("label_41")
        self.label_43 = QtWidgets.QLabel(Dialog)
        self.label_43.setGeometry(QtCore.QRect(370, 310, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setText(global_list[51])
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(Dialog)
        self.label_44.setGeometry(QtCore.QRect(477, 310, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setText(global_list[52])
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setWordWrap(True)
        self.label_44.setObjectName("label_44")
        self.label_42 = QtWidgets.QLabel(Dialog)
        self.label_42.setGeometry(QtCore.QRect(270, 310, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setText(global_list[50])
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setWordWrap(True)
        self.label_42.setObjectName("label_42")
        self.label_48 = QtWidgets.QLabel(Dialog)
        self.label_48.setGeometry(QtCore.QRect(890, 310, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setText(global_list[56])
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setWordWrap(True)
        self.label_48.setObjectName("label_48")
        self.label_47 = QtWidgets.QLabel(Dialog)
        self.label_47.setGeometry(QtCore.QRect(790, 310, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setText(global_list[55])
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setWordWrap(True)
        self.label_47.setObjectName("label_47")
        self.label_46 = QtWidgets.QLabel(Dialog)
        self.label_46.setGeometry(QtCore.QRect(687, 310, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setText(global_list[54])
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setWordWrap(True)
        self.label_46.setObjectName("label_46")
        self.label_49 = QtWidgets.QLabel(Dialog)
        self.label_49.setGeometry(QtCore.QRect(997, 310, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setText(global_list[57])
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setWordWrap(True)
        self.label_49.setObjectName("label_49")
        self.label_45 = QtWidgets.QLabel(Dialog)
        self.label_45.setGeometry(QtCore.QRect(580, 310, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setText(global_list[53])
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setWordWrap(True)
        self.label_45.setObjectName("label_45")
        self.label_511 = QtWidgets.QLabel(Dialog)
        self.label_511.setGeometry(QtCore.QRect(1210, 370, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_511.setFont(font)
        self.label_511.setText(global_list[71])
        self.label_511.setAlignment(QtCore.Qt.AlignCenter)
        self.label_511.setWordWrap(True)
        self.label_511.setObjectName("label_511")
        self.label_55 = QtWidgets.QLabel(Dialog)
        self.label_55.setGeometry(QtCore.QRect(580, 370, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_55.setFont(font)
        self.label_55.setText(global_list[65])
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setWordWrap(True)
        self.label_55.setObjectName("label_55")
        self.label_52 = QtWidgets.QLabel(Dialog)
        self.label_52.setGeometry(QtCore.QRect(270, 370, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setText(global_list[62])
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setWordWrap(True)
        self.label_52.setObjectName("label_52")
        self.label_54 = QtWidgets.QLabel(Dialog)
        self.label_54.setGeometry(QtCore.QRect(477, 370, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_54.setFont(font)
        self.label_54.setText(global_list[64])
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setWordWrap(True)
        self.label_54.setObjectName("label_54")
        self.label_56 = QtWidgets.QLabel(Dialog)
        self.label_56.setGeometry(QtCore.QRect(687, 370, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_56.setFont(font)
        self.label_56.setText(global_list[66])
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setWordWrap(True)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(Dialog)
        self.label_57.setGeometry(QtCore.QRect(790, 370, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_57.setFont(font)
        self.label_57.setText(global_list[67])
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setWordWrap(True)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(Dialog)
        self.label_58.setGeometry(QtCore.QRect(890, 370, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_58.setFont(font)
        self.label_58.setText(global_list[68])
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setWordWrap(True)
        self.label_58.setObjectName("label_58")
        self.label_53 = QtWidgets.QLabel(Dialog)
        self.label_53.setGeometry(QtCore.QRect(370, 370, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setText(global_list[63])
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setWordWrap(True)
        self.label_53.setObjectName("label_53")
        self.label_510 = QtWidgets.QLabel(Dialog)
        self.label_510.setGeometry(QtCore.QRect(1102, 370, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_510.setFont(font)
        self.label_510.setText(global_list[70])
        self.label_510.setAlignment(QtCore.Qt.AlignCenter)
        self.label_510.setWordWrap(True)
        self.label_510.setObjectName("label_510")
        self.label_50 = QtWidgets.QLabel(Dialog)
        self.label_50.setGeometry(QtCore.QRect(60, 370, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_50.setFont(font)
        self.label_50.setText(global_list[60])
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setWordWrap(True)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(Dialog)
        self.label_51.setGeometry(QtCore.QRect(170, 370, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_51.setFont(font)
        self.label_51.setText(global_list[61])
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setWordWrap(True)
        self.label_51.setObjectName("label_51")
        self.label_59 = QtWidgets.QLabel(Dialog)
        self.label_59.setGeometry(QtCore.QRect(997, 370, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_59.setFont(font)
        self.label_59.setText(global_list[69])
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setWordWrap(True)
        self.label_59.setObjectName("label_59")
        self.saveimg = QtWidgets.QPushButton(Dialog)
        self.saveimg.setGeometry(QtCore.QRect(310, 570, 301, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.saveimg.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.saveimg.setFont(font)
        self.saveimg.setText("")
        self.saveimg.setAutoDefault(False)
        self.saveimg.setFlat(True)
        self.saveimg.setObjectName("saveimg")
        self.savepdf = QtWidgets.QPushButton(Dialog)
        self.savepdf.setGeometry(QtCore.QRect(710, 570, 301, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.savepdf.setPalette(palette)
        self.savepdf.setText("")
        self.savepdf.setAutoDefault(False)
        self.savepdf.setFlat(True)
        self.savepdf.setObjectName("savepdf")
        self.Group = QtWidgets.QLabel(Dialog)
        self.Group.setGeometry(QtCore.QRect(510, 6, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Group.setFont(font)
        self.Group.setText(header_data[0])
        self.Group.setAlignment(QtCore.Qt.AlignCenter)
        self.Group.setObjectName("Group")
        self.Section = QtWidgets.QLabel(Dialog)
        self.Section.setGeometry(QtCore.QRect(770, 6, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Section.setFont(font)
        self.Section.setText(header_data[1])
        self.Section.setAlignment(QtCore.Qt.AlignCenter)
        self.Section.setObjectName("Section")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Your section table"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><img src=\"PNG/individual_table.png\"/></p></body></html>"))
        #self.label_86.setText(_translate("Dialog", "<html><head/><body><p><img src=\"PNG\Save Image.png\"/></p></body></html>"))
        #self.label_87.setText(_translate("Dialog", "<html><head/><body><p><img src=\"PNG\Save PDF.png\"/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

